import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./component/Header";
import Sidebar from "./component/Sidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

async function fetchSidebarData() {
  const res = await fetch(`${process.env.NEXT_PUBLIC_BASE_URL}/api/sidebar`, {
    cache: "no-store",
  });

  if (!res.ok) {
    console.error("Failed to fetch sidebar data");
    return [];
  }

  return res.json();
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const menus = await fetchSidebarData();
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="flex">
          <Sidebar menus={menus} />
          <div className="flex-1 flex flex-col">
            <Header />
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
